baseURL = 'petitengineer.com'
languageCode = 'en-us'
title = "Jonathan Horton"
theme = 'aether'
description = 'test'

[params]
  brand = "JHorton"
#  description = "A blog that discusses techonology."
#  bgimg = "Path, within the 'assets' folder, of the image used for the page background - optional"
  headshotimg = "Main-Page/Headshot.JPG"
  headshotalt = "Jonathan Horton is an electrical engineer passionate about hardware design and robotics."
  homeblobtext = "Test"

  rssinmenu = true
  github = "https://github.com/petitengineer"
  linkedin = "www.linkedin.com/in/jonathan-horton-elg"

#[markup]
#  [markup.highlight]
#    style = "igor"
