baseURL = 'https://petitengineer.github.io/'
languageCode = 'en-us'
title = "Jonathan Horton"
theme = 'aether'

#Parameters
[params]
  brand = "JHorton"
  description = "A blog that discusses techonology."
  headshotimg = "main-page/headshot.JPG"
  headshotalt = "Jonathan Horton is an electrical engineer passionate about hardware design and robotics."
  rssinmenu = true
  github = "https://github.com/petitengineer"
  linkedin = "www.linkedin.com/in/jonathan-horton-elg"

[markup]
  [markup.highlight]
    style = "igor"
